# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinact < Formula
  desc "Pin GitHub Actions versions"
  homepage "https://github.com/suzuki-shunsuke/pinact"
  version "2.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v2.2.1/pinact_darwin_amd64.tar.gz"
      sha256 "77bdc618826b35c55ec95b04bbe5ce849739416930be4ee083ebff6e0e2764e3"

      def install
        bin.install "pinact"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v2.2.1/pinact_darwin_arm64.tar.gz"
      sha256 "c31d3ba6c51d44461e4dfeb27b9a93436c7f708da7ef2eeee1e01b90ae7fd45e"

      def install
        bin.install "pinact"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/pinact/releases/download/v2.2.1/pinact_linux_amd64.tar.gz"
        sha256 "30da95ae20a23940e8f63d7d7ee58c79ebbde25ee60d0d934e6964a0e4c95c28"

        def install
          bin.install "pinact"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/pinact/releases/download/v2.2.1/pinact_linux_arm64.tar.gz"
        sha256 "414735fde9f79395b246ea17347b8e7d2da1a49cda9ed45d72e2ee889a0320db"

        def install
          bin.install "pinact"
        end
      end
    end
  end

  test do
    system "#{bin}/pinact --version"
  end
end
