# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinact < Formula
  desc "Pin GitHub Actions versions"
  homepage "https://github.com/suzuki-shunsuke/pinact"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v1.0.0/pinact_darwin_amd64.tar.gz"
      sha256 "9caf9c7f17aea625b1da1dd1ef5b2988069c65df0ca43c219d17c07e9da8cd1b"

      def install
        bin.install "pinact"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v1.0.0/pinact_darwin_arm64.tar.gz"
      sha256 "73d06ea7c7be9965c47863b2d9c04f298ae1d37edc18e162c540acb4ac030314"

      def install
        bin.install "pinact"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/pinact/releases/download/v1.0.0/pinact_linux_amd64.tar.gz"
        sha256 "f6cf07459807f67e79ff4e7e60d414d28c7d5ac916ee3ddea561738d27c3e6a7"

        def install
          bin.install "pinact"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/pinact/releases/download/v1.0.0/pinact_linux_arm64.tar.gz"
        sha256 "1bfaed4e7b53b15199772688febe4cb2a0aa8313b964b06f13767b4e5c3a31e3"

        def install
          bin.install "pinact"
        end
      end
    end
  end

  test do
    system "#{bin}/pinact --version"
  end
end
