# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinact" do
  name "pinact"
  desc "Pin GitHub Actions versions"
  homepage "https://github.com/suzuki-shunsuke/pinact"
  version "3.4.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinact"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_amd64.tar.gz"
      sha256 "13b6167ea25befa2115f7e44bba2cff5b2fb6448d98b3bd7b4592eda973b7b12"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_arm64.tar.gz"
      sha256 "1d6e8239537eada29e94285ea1e5d1a1db27db9320a9621c9e1d6427f118aee4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_amd64.tar.gz"
      sha256 "1876ddd571ba8452c07a1b9b9a325bdfe074a467be9a81f3fd42743bf6043618"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_arm64.tar.gz"
      sha256 "6aefea25eb7b9d1c7d03e6b42564f20d2f30efefecb991428b33348418397c14"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinact"]
    end
  end

  # No zap stanza required
end
