# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinact" do
  version "4.1.1"

  on_macos do
    on_intel do
      sha256 "513678fdb0bb59b2742dd06d28f0ee851496a83ba939954009aa6be53f5aec9c"
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c13998c9f0dd09d8973700938aa5f6ac52a1db4e94d4f578d8cc976cda478614"
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1cffebe5704b74e2e5f8a864efb9f7e54768972dc686188c008033fb1797841"
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd1f29908319ed3e59f9fe6b39196efbb76936357f3bd741cd759a96306ae8d8"
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_arm64.tar.gz"
    end
  end

  name "pinact"
  desc "Pin GitHub Actions versions"
  homepage "https://github.com/suzuki-shunsuke/pinact"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinact"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinact"]
    end
  end

  # No zap stanza required

end
