# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinact" do
  name "pinact"
  desc "Pin GitHub Actions versions"
  homepage "https://github.com/suzuki-shunsuke/pinact"
  version "3.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinact"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_amd64.tar.gz"
      sha256 "21507ef818d6ff254cc8623a9dbd969547ab7925c86f4bd481052baf502f2baa"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_darwin_arm64.tar.gz"
      sha256 "58cd5ed8043124b82d9ec5b8507ff1ddbed83920baf18179053203c01dc502c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_amd64.tar.gz"
      sha256 "8132af84fb5c0991fd88e5d5d552b59ab0fd9d073c85d5f457d52ad8d33f648f"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/pinact/releases/download/v#{version}/pinact_linux_arm64.tar.gz"
      sha256 "fdb2112123538686f36a7dff80278fd60d0f79d36da05dda16f0538f8ad490e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinact"]
    end
  end

  # No zap stanza required
end
